{% set name = "wagtail-pdf" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/donhauser/wagtail-pdf/archive/{{ version }}.tar.gz
  sha256: 54ad1d87ae6795e4572bb7b98cc072f07aa26517ac94e99f09a740733e61d760

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail
    - django-weasyprint

test:
  imports:
    - wagtail_pdf_view
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/donhauser/wagtail-pdf
  summary: PDF rendering views for the Wagtail CMS
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
