{% set name = "wagtail-pdf" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/donhauser/wagtail-pdf/archive/{{ version }}.tar.gz
  sha256: f87fff035cbf88c600bb2947096b24e35a9ba5640d9c210bd38a1dfabd45857d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - wagtail

test:
  imports:
    - wagtail_pdf_view
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/donhauser/wagtail-pdf
  summary: PDF rendering views for the Wagtail CMS
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
